const ERROR = {
   NOT_FOUND: "NOT_FOUND",
   UNAUTHORIZED: "UNAUTHORIZED",
   FORBIDDEN: "FORBIDDEN",
   INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
   AUTH_NOT_FOUND: "AUTH_NOT_FOUND",
};

export default ERROR;
